# Generated by Django 4.2.7 on 2025-05-08 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room')], help_text='Type of room the student is applying for', max_length=10)),
                ('semester', models.CharField(help_text='Semester (e.g., 2023/2024 Semester 1)', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the application', max_length=10)),
                ('date_applied', models.DateTimeField(auto_now_add=True, help_text='When the application was submitted')),
                ('student', models.ForeignKey(help_text='The student who submitted this application', on_delete=django.db.models.deletion.CASCADE, related_name='hostel_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
