# Generated by Django 4.2.7 on 2025-05-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('electrical', 'Electrical Issue'), ('plumbing', 'Plumbing Issue'), ('furniture', 'Furniture Repair'), ('cleaning', 'Cleaning Request'), ('other', 'Other Issue')], help_text='Type of maintenance request', max_length=20)),
                ('room_number', models.CharField(help_text='Room number where the issue is located', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of the maintenance issue')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the request', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=15)),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='When the request was submitted')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
                ('staff_notes', models.TextField(blank=True, help_text='Notes or comments from staff about this request', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student who submitted this request', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
