# Generated by Django 4.2.7 on 2025-05-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0002_maintenancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Room number (e.g., A101)', max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room')], help_text='Type of room', max_length=10)),
                ('has_aircon', models.BooleanField(default=False, help_text='Whether the room has air conditioning')),
                ('has_attached_bathroom', models.BooleanField(default=False, help_text='Whether the room has an attached bathroom')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', help_text='Current status of the room', max_length=15)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Maximum number of students that can stay in this room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the assignment')),
                ('end_date', models.DateField(help_text='End date of the assignment')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the assignment', max_length=10)),
                ('date_assigned', models.DateTimeField(auto_now_add=True, help_text='When the assignment was created')),
                ('room', models.ForeignKey(help_text='The room assigned to the student', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hostel.room')),
                ('student', models.ForeignKey(help_text='The student assigned to this room', on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in RM', max_digits=10)),
                ('payment_period_start', models.DateField(help_text='Start date of the payment period')),
                ('payment_period_end', models.DateField(help_text='End date of the payment period')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('tng', "Touch 'n Go")], help_text='Method of payment', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the payment', max_length=10)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction reference number (for TNG payments)', max_length=100, null=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True, help_text='When the payment was made')),
                ('room_assignment', models.ForeignKey(help_text='The room assignment this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hostel.roomassignment')),
                ('student', models.ForeignKey(help_text='The student making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
