# Generated by Django 4.2.7 on 2025-05-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_hostelapplication_date_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hostelapplication',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostelapplication',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hostel.semester'),
        ),
    ]
