# Generated by Django 4.2.7 on 2025-05-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_semester_alter_hostelapplication_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapplication',
            name='end_date',
            field=models.DateField(default='2024-06-30'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='start_date',
            field=models.DateField(default='2024-06-01'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
