# Generated by Django 4.2.7 on 2025-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_remove_room_has_aircon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
