# Generated by Django 4.2.7 on 2025-06-12 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_semester_application_end_semester_application_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='application_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='application_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
