# Generated by Django 4.2.7 on 2025-06-12 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_alter_semester_application_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='application_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='application_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
