# Generated by Django 5.2.3 on 2025-06-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_semester_application_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelapplication',
            name='is_auto_rejected',
            field=models.BooleanField(default=False, help_text='Auto-rejected due to quota reached'),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostelapplication',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special requests by the student', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='quota_double',
            field=models.PositiveIntegerField(default=0, help_text='Quota for double rooms (number of rooms, not students)'),
        ),
        migrations.AddField(
            model_name='semester',
            name='quota_single',
            field=models.PositiveIntegerField(default=0, help_text='Quota for single rooms'),
        ),
        migrations.AlterField(
            model_name='hostelapplication',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hostelapplication',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room (1 person per room)'), ('double', 'Double Room (2 persons per room)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostelapplication',
            name='start_date',
            field=models.DateField(),
        ),
    ]
