# Generated by Django 5.2.3 on 2025-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_hostelapplication_is_auto_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=10),
        ),
    ]
