# Generated by Django 4.2.7 on 2025-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(blank=True, choices=[('local', 'Local Student'), ('international', 'International Student')], help_text='Type of student (local or international)', max_length=15, null=True),
        ),
    ]
